### ISSUE TITLE
Typo in LSM_spindle_probabilities

### ISSUE THREAD

**Issue by erss** [Mark-Kramer/Spindle-Detector-Method#5]
In lines 29 & 30, there is a typo in 'MinPeakPromience' and should be 'MinPeakProminence.'

Also in both lines, the boolean 'isempty(find(strcmp(options, 'MinPeakProminence')))' is always 1.  Might be better to use: isfield(options,'MinPeakProminence')

**Comment by Mark-Kramer** [comment]
Fixed as you suggested.  Thank you!
